# Generated by Django 3.2.7 on 2022-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooluser',
            name='gravatar_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
