# Generated by Django 3.2.7 on 2022-11-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0005_cooluser_gravatar_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooluser',
            name='github_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooluser',
            name='last_github_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
