# Generated by Django 3.2.7 on 2022-11-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0006_auto_20221122_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
